### PR TITLE
Include B1map in anatomical data listing

### PR DESCRIPTION
**Pull request by Gilles86**
We use B1 maps for improving the T1 estimation of MP2RAGEs. Noted that they were not included yet in current draft.

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
> Data acquired to correct for B0 inhomogeneities can come in different forms.`

This is how field maps is currently described in the mainspec. It accounts for 4 different scenarios, all focusing on B0 maps. Plus there are some fixed suffixes such as `magnitudeN`, `phaseN` and `fieldmap`. 

Should we suggest changes there to make the whole spec more compliant, or just leave it as is?

**Comment by Gilles86** [comment]
I'm not sure. That part of the spec was clearly written from the fMRI use-case and only one out of 4 scenarios talks about a proper, quantitative B0map. I think we should not touch hat part of the spec. To be honest, I would even argue again to put he B1map "just" in the `anat`-folder, to keep things simple. What do you think?

**Comment by agahkarakuzu** [comment]
@Gilles86 now that I better see your point. 

As long as we clearly explain the reasons why these maps are not going into the `fmap` folder, putting `B1map` in the `anat` folder looks like a good idea. Can we add `B0map` in this case ass well?

**Comment by tiborauer** [comment]
Is B1map a separate acquisition, or part of the MP2RAGE? If it is a separate one (just like the fieldmaps for fMRI), then I cannot see why it should not go to `fmap`

**Comment by Gilles86** [comment]
It is a different acquisition altogether, with, as I understood, many possible approaches and sequences actually.

**Comment by KirstieJane** [comment]
Heya! Thanks for having this discussion @Gilles86 @tiborauer & @agahkarakuzu.

I think we *should* update the fieldmap section (https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fieldmap-data). Why not just add a fifth example?

**Comment by agahkarakuzu** [comment]
@KirstieJane should we just add descriptions only for `B1Map` itself or also for descriptions for source files that **may** be used to create them (e.g. `Double angle mapping` using segmented EPI)? 

The `fieldmap` section is already a mixture of both (I guess, I am a bit lost in that section).

**Comment by Gilles86** [comment]
> The fieldmap section is already a mixture of both (I guess, I am a bit lost in that section).

Also, it explicitly only deals with B0 maps:
>Data acquired to correct for B0 inhomogeneities can come in different forms. The current version of this standard considers four different scenarios.

I guess we could add a fifth category wit suffix `_b1map`.

**Comment by Gilles86** [comment]
Let's close this and let it be superseded by pull request #48

**Pull request closed without merging**
